name: tests

on: 
  push:
      branches:
          - main

          
jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS
            os: macos-latest
            php: '8.4'
            phpunit: '11.5'
          - name: macOS-x86_64
            os: macos-13
            php: '8.4'
            phpunit: '11.5'

    steps:
      - name: Setup PHP ${{ matrix.php }}
        if: ${{ !startsWith(matrix.os, 'macos-') }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # PHP Extras
          coverage: none
          #tools: composer, phpunit:${{ matrix.phpunit }}, phpstan
          tools: composer
          #ini-values: "memory_limit=512M"
          extensions: ffi

      - name: Setup PHP ${{ matrix.php }} (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          # PHP Extras
          coverage: none
          tools: composer, phpstan
          #ini-values: "memory_limit=512M"
          extensions: ffi

      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Composer
        run: composer update

      - name: PHP Static Analysys
        run: phpstan

      - name: PHPUnit Tests
        if: ${{ !startsWith(matrix.os, 'macos-') }}
        run: phpunit -c tests

      - name: PHPUnit Tests(macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: |
          composer require --dev phpunit/phpunit=${{ matrix.phpunit }}.*
          phpunit -c tests
